services:

  db:
    image: postgres
    restart: always
    container_name: pg-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080