# ? resource https://docs.agno.com/agents/knowledge#vector-databases
services:

  db:
    image: agnohq/pgvector:16
    restart: always
    container_name: pg-db
    volumes:
      - ./pgvolume:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080